config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts do
    resources :comments, :shallow => true
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  # has_many :tags
  # has_many :posts, :through => :tags
  has_and_belongs_to_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # belongs_to :post
  belongs_to :commentable, :polymorphic => true
  has_many :subcomments, :class_name => "Reply", :foreign_key => "parent_comment_id"
  belongs_to :parent_comment, :class_name => "Comment"
end

app/models/photo_post.rb
class PhotoPost < Post
end

app/models/post.rb
class Post < ActiveRecord::Base
  # has_one :comment
  has_many :comments, :as => :commentable, :dependent => :restrict_with_exception
  has_many :authors

  # has_many :tags
  # has_many :categories, :through => :tags

  has_and_belongs_to_many :categories
  validates :title, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/video_post.rb
class VideoPost < Post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :author)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.haml
%strong
  = comment.body
  = link_to "Delete Comment", comment_path(comment), :method => :delete
%br

app/views/comments/_form.html.haml
= simple_form_for [@post, @post.comments.build] do |comment|
  = comment.input :body
  = comment.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |post|
  - if @post.errors.any?
    %div
      %h2 
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li
            = msg
  = post.input :title
  = post.input :body
  = post.button :submit

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.haml
= render "form"

app/views/posts/index.html.haml
%h1 Posts#index
= link_to "New Post", new_post_path
%br
- @posts.each do |post|
  = link_to "#{post.title}", post_path(post)
  %br

app/views/posts/new.html.haml
= render "form"

app/views/posts/show.html.haml
%h2
  = @post.title
%h2
  = @post.body

%h1 Comments
= render :partial => "comments/comment", :collection => @post.comments

= render "comments/form"

= link_to "Edit Post", edit_post_path(@post)
= link_to "Delete Post", post_path(@post), :method => :delete

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>